import type { Category, Dish } from '../types/menu';
import type { Order } from '../types/order';
import type { Reservation } from '../types/reservation';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-starters',
    name: 'Appetizers',
    slug: 'starters',
    displayOrder: 1,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop',
    description: 'Crisp artisanal bites and palate openers made with seasonal garden herbs.',
  },
  {
    id: 'cat-mains',
    name: 'Main Courses',
    slug: 'mains',
    displayOrder: 2,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    description: 'Slow-roasted meats, seared poultry, and ocean-fresh seafood creations.',
  },
  {
    id: 'cat-pasta',
    name: 'Pasta',
    slug: 'pasta',
    displayOrder: 3,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?q=80&w=800&auto=format&fit=crop',
    description: 'Handcrafted pasta ribbons tossed in aged cheeses and velvety reductions.',
  },
  {
    id: 'cat-pizza',
    name: 'Pizza',
    slug: 'pizza',
    displayOrder: 4,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=800&auto=format&fit=crop',
    description: 'Fermented dough stone-baked at 800°F with San Marzano tomatoes and fior di latte.',
  },
  {
    id: 'cat-desserts',
    name: 'Desserts',
    slug: 'desserts',
    displayOrder: 5,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?q=80&w=800&auto=format&fit=crop',
    description: 'Molten chocolate indulgence, silky gelato, and crisp caramelized confections.',
  },
  {
    id: 'cat-beverages',
    name: 'Beverages',
    slug: 'beverages',
    displayOrder: 6,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop',
    description: 'Botanical infusions, smoked cold brews, and signature crafted mocktails.',
  },
];

export const MOCK_DISHES: Dish[] = [
  {
    id: 'dish-01',
    categoryId: 'cat-mains',
    categorySlug: 'mains',
    name: 'Truffle Mushroom Risotto',
    slug: 'truffle-mushroom-risotto',
    description: 'Acquerello carnaroli rice, wild French morels, shaved black winter truffles, and 24-month Parmigiano-Reggiano emulsion.',
    price: 34.00,
    mediaUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?q=80&w=600&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    featured: true,
    calories: 460,
    dietaryTags: ['SIGNATURE', 'CHEFS_CHOICE', 'VEGETARIAN', 'GLUTEN_FREE'],
    allergens: ['Dairy'],
    winePairing: 'Barolo Riserva 2018',
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-truffle',
        title: 'Truffle Shaving Extra',
        required: false,
        options: [
          { id: 'opt-extra-truffle', name: 'Fresh Shaved Black Truffle (+5g)', price: 12.00 },
          { id: 'opt-white-truffle', name: 'Alba White Truffle Infusion', price: 18.00 },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dish-02',
    categoryId: 'cat-mains',
    categorySlug: 'mains',
    name: 'Grilled Herb Chicken',
    slug: 'grilled-herb-chicken',
    description: 'Organic free-range chicken breast flame-grilled over citrus wood with rosemary thyme reduction, roasted heirloom carrots, and potato mousseline.',
    price: 29.00,
    mediaUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=600&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    featured: true,
    calories: 520,
    dietaryTags: ['SIGNATURE', 'GLUTEN_FREE'],
    allergens: ['Dairy'],
    winePairing: 'Domaine Dujac Morey-Saint-Denis 2020',
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-temp',
        title: 'Herb Butter Sauce',
        required: false,
        options: [
          { id: 'opt-garlic-butter', name: 'Garlic Herb Compound Butter', price: 3.50 },
          { id: 'opt-chimichurri', name: 'Botanical Chimichurri', price: 3.00 },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dish-03',
    categoryId: 'cat-pasta',
    categorySlug: 'pasta',
    name: 'Creamy Alfredo Pasta',
    slug: 'creamy-alfredo-pasta',
    description: 'House-extruded tagliatelle tossed in rich cultured Normandy butter, double cream, cracked tellicherry pepper, and shaved Pecorino Romano.',
    price: 26.00,
    mediaUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=600&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    featured: true,
    calories: 610,
    dietaryTags: ['SIGNATURE', 'VEGETARIAN'],
    allergens: ['Dairy', 'Gluten'],
    winePairing: 'Gavi di Gavi La Scolca 2021',
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-protein',
        title: 'Add Protein',
        required: false,
        options: [
          { id: 'opt-grilled-prawns', name: 'Charred Garlic Prawns (3 pcs)', price: 9.00 },
          { id: 'opt-smoked-pancetta', name: 'Crispy Smoked Pancetta', price: 5.00 },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dish-04',
    categoryId: 'cat-pizza',
    categorySlug: 'pizza',
    name: 'Wood-fired Margherita',
    slug: 'wood-fired-margherita',
    description: 'Naturally fermented sourdough crust, San Marzano D.O.P. tomato coulis, fresh fior di latte mozzarella, cold-pressed olive oil, and sweet basil leaves.',
    price: 22.00,
    mediaUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=600&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    featured: true,
    calories: 680,
    dietaryTags: ['SIGNATURE', 'VEGETARIAN'],
    allergens: ['Dairy', 'Gluten'],
    winePairing: 'Chianti Classico Gran Selezione 2019',
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-cheese',
        title: 'Cheese Upgrade',
        required: false,
        options: [
          { id: 'opt-buffalo-mozz', name: 'Bufala Campana D.O.P.', price: 4.50 },
          { id: 'opt-spicy-honey', name: 'Calabrian Chili Hot Honey Drizzle', price: 2.50 },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dish-05',
    categoryId: 'cat-desserts',
    categorySlug: 'desserts',
    name: 'Chocolate Lava Cake',
    slug: 'chocolate-lava-cake',
    description: 'Warm molten cake made with single-origin Valrhona 72% dark chocolate, liquid ganache core, Madagascar Bourbon vanilla bean gelato, and gold dust.',
    price: 18.00,
    mediaUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=600&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    featured: true,
    calories: 490,
    dietaryTags: ['SIGNATURE', 'VEGETARIAN', 'CHEFS_CHOICE'],
    allergens: ['Dairy', 'Eggs', 'Gluten'],
    winePairing: 'Taylor Fladgate 20 Year Old Tawny Port',
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dish-06',
    categoryId: 'cat-starters',
    categorySlug: 'starters',
    name: 'Crispy Artichoke Hearts',
    slug: 'crispy-artichoke-hearts',
    description: 'Baby artichokes flash-fried with meyer lemon zest, whipped sheep ricotta dip, and toasted pine nuts.',
    price: 19.00,
    mediaUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=600&auto=format&fit=crop',
    calories: 280,
    dietaryTags: ['VEGETARIAN', 'GLUTEN_FREE'],
    allergens: ['Dairy', 'Tree Nuts'],
    winePairing: 'Sancerre Blanc 2022',
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dish-07',
    categoryId: 'cat-beverages',
    categorySlug: 'beverages',
    name: 'Craftsland Golden Nectar',
    slug: 'craftsland-golden-nectar',
    description: 'Cold-pressed passion fruit, roasted yuzu, effervescent ginger botanical brew, edible 24k gold flakes, and rosemary mist.',
    price: 14.00,
    mediaUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=600&auto=format&fit=crop',
    calories: 140,
    dietaryTags: ['SIGNATURE', 'VEGAN', 'GLUTEN_FREE'],
    allergens: [],
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dish-08',
    categoryId: 'cat-pizza',
    categorySlug: 'pizza',
    name: 'Spicy Diavola & Nduja',
    slug: 'spicy-diavola-nduja',
    description: 'Artisanal spicy calabrese salami, spreadable nduja sausage, crushed chili oil, smoked provolone, and wildflower honey.',
    price: 25.00,
    mediaUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=600&auto=format&fit=crop',
    calories: 740,
    dietaryTags: ['SPICY'],
    allergens: ['Dairy', 'Gluten', 'Pork'],
    isAvailable: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-8801',
    orderNumber: 'CRF-101',
    orderType: 'DINE_IN',
    tableNumber: 'Table 4',
    orderStatus: 'PREPARING',
    paymentStatus: 'PAID',
    items: [
      {
        id: 'item-1',
        orderId: 'ord-8801',
        dishId: 'dish-01',
        dishName: 'Truffle Mushroom Risotto',
        quantity: 2,
        unitPrice: 34.00,
        itemSubtotal: 68.00,
        selectedModifiers: [],
      },
      {
        id: 'item-2',
        orderId: 'ord-8801',
        dishId: 'dish-05',
        dishName: 'Chocolate Lava Cake',
        quantity: 1,
        unitPrice: 18.00,
        itemSubtotal: 18.00,
        selectedModifiers: [],
      }
    ],
    subtotal: 86.00,
    taxAmount: 7.31,
    deliveryFee: 0.00,
    discountAmount: 0.00,
    tipAmount: 15.00,
    totalAmount: 108.31,
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord-8802',
    orderNumber: 'CRF-102',
    orderType: 'DELIVERY',
    deliveryAddress: '742 Evergreen Terrace, Apt 4B, Metropolis 10001',
    orderStatus: 'PENDING',
    paymentStatus: 'PAID',
    items: [
      {
        id: 'item-3',
        orderId: 'ord-8802',
        dishId: 'dish-02',
        dishName: 'Grilled Herb Chicken',
        quantity: 1,
        unitPrice: 29.00,
        itemSubtotal: 29.00,
        selectedModifiers: [],
      },
      {
        id: 'item-4',
        orderId: 'ord-8802',
        dishId: 'dish-04',
        dishName: 'Wood-fired Margherita',
        quantity: 1,
        unitPrice: 22.00,
        itemSubtotal: 22.00,
        selectedModifiers: [],
      }
    ],
    subtotal: 51.00,
    taxAmount: 4.34,
    deliveryFee: 12.00,
    discountAmount: 0.00,
    tipAmount: 8.00,
    totalAmount: 75.34,
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  }
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'res-501',
    bookingReference: 'CRF-RES-501',
    partySize: 4,
    reservationDate: new Date().toISOString().split('T')[0],
    reservationTime: '19:30',
    seatingSection: 'MAIN_DINING',
    status: 'CONFIRMED',
    guestName: 'Eleanor Vance',
    guestEmail: 'eleanor@vance.com',
    guestPhone: '+1 555-404-9912',
    specialRequests: 'Anniversary celebration. Window table preferred.',
    createdAt: new Date().toISOString(),
  }
];
